//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int id { get; set; }
        public string exam_code { get; set; }
        public string question { get; set; }
        public string option_A { get; set; }
        public string option_B { get; set; }
        public string option_C { get; set; }
        public string option_D { get; set; }
        public string correct_answer { get; set; }
    }
}
