//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Answers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string q_id { get; set; }
        public string exam_code { get; set; }
        public string option { get; set; }
    }
}
